---
title: "Statistical Inference Course Project"
author: "Victor Bucha"
date: "5 October, 2015"
output: html_document
---
#Part 1
##Overview
We simulated 1000 means of 40 exponentials. Sample mean and standard deviation agree with the theory and close to both theoretical mean and standard deviation. It is shown the distribution of the mean of 40 exponentials is approximatly normal with mean=4.974 and sd=0.7713.

##Simulations
In this simulation, we simulated 1000 means of 40 exponetials. Lambda was set to 0.2. As a result we get matrix sim with 1000 rows and 40 columns.
```{R Simulate 40 exponetials}
set.seed(1234)
nosim<-1000 # number of simulations
n<-40 # number of exponentials
lambda<-.2 #set lambda

#simulate 1000 means of 40 exponentials
sim<-matrix(rexp(nosim*n,lambda),nosim)
```

##Sample Mean versus Theoretical Mean
Theoretical mean of exponetial distribution is equal to 1/lambda=0.5. Then we investigated distribution of averages of 40 exponentials. Its sample mean should be centered at what distribution estimating. We got sample mean close to theoretical mean as it's shown at figure bellow.
```{R Show the sample mean }
means<-apply(sim,1,mean) #estimate n means
mean_theory<-1/lambda #theoretical mean 
mean_sample<-mean(means) #sample mean 

#draw histogram of means
library(ggplot2)
ggplot()+aes(means)+
  geom_histogram(binwidth=0.25, colour="black", fill="white")+
  geom_vline(aes(xintercept = mean_theory,colour="Theoretical"),
             size=2.5,linetype=2,show_guide = TRUE)+
  geom_vline(aes(xintercept = mean_sample,colour="Sample"),
             size=1.2,linetype=2,show_guide = TRUE)+
  scale_colour_manual(name="Mean", values=c(Theoretical="red",Sample="blue"))+
  labs(title="Histogram of averages of 40 exponentials",x="Value",y="Frequency")+
  annotate("text",label=paste("Theoretical mean:",as.character(mean_theory)),
           x=mean_theory+1.7,y=120,colour="red")+
  annotate("text",label=paste("Sample mean:",format(mean_sample,digits=4)),
           x=mean_theory+1.75,y=113,colour="blue")
```

##Sample Variance versus Theoretical Variance
Theoretical variance of the sample mean is the population variance divided by n. We estimated standart error by dividing  theoretical standard deviaition equal to 1/lambda by square root of n equal to 40. Obtained theoretical standart deviation was compared with sample standard deviation. They were close as theory predicted.

```{R Show the sample variance }
sd_sample<-sd(means)
sd_theory<-1/lambda/sqrt(n)

#draw histogram
ggplot()+aes(means)+
  geom_histogram(binwidth=0.25, colour="black", fill="blue",alpha=0.2,aes(y=..density..))+
  stat_function(fun=dnorm, args=list(mean=mean_theory, sd=sd_theory),color="red",size=1.5)+
  labs(title="Distribution of means of 40 exponentials",x="Value",y="Density")+
  annotate("text",label=paste("Theoretical std:",format(sd_theory,digits=4)),
           x=6.7,y=0.5,colour="red")+
  annotate("text",label=paste("Sample std:",format(sd_sample,digits=4)),
           x=6.55,y=0.46,colour="blue")
```

##Distribution
At first let us plot distribution of exponentials obtained on the first simulation step of assignment. It follows exponetial law as we can see from figure bellow.

```{R Show distributions }
ggplot()+aes(as.vector(sim))+
  geom_histogram(binwidth=2.5, colour="black", fill="white",aes(y=..density..))+
  labs(title="Distribution of exponentials",x="Value",y="Density")
```

Central Limit Theorem states that the distribution of averages of iid variables become that of a standard normal. Bellow figure shows the distribution of means of 40 exponentials. The shape of distribution is very close to normal. So we obtained result that agrees with a theory.
```{R Show distribution of averages }
#draw histogram
ggplot()+aes(means)+
  geom_histogram(binwidth=0.25, colour="black", fill="white",aes(y=..density..))+
  stat_function(fun=dnorm, args=list(mean=mean_theory, sd=sd_theory),color="red",size=1.5)+
  labs(title="Distribution of means of 40 exponentials",x="Value",y="Density")
```

#Part 2

## Exploratory plot 
At first let us look at the data. Bellow plot shows effect of vitamin C on tooth growth. We smoothed data with linear model. It's interesting that for dose levels 0.5 and 1.0 ascorbic acid shows lower perfomance than orange juice. However for dose level 2.0 both supplemnets shows relativly the same growth performance. Let us test our hypotheses **assuming different variances for OJ and VC supplements.**
   
```{R load data}
data("ToothGrowth")
ggplot(data=ToothGrowth,aes(x=dose,y=len,color=supp))+
        geom_point(size=3,alpha=0.7)+geom_smooth(size=1,se=FALSE,method=lm)+
        labs(title="The Effect of Vitamin C on Tooth Growth",x="Dose",y="Length")+
        scale_color_discrete("Supplement",labels=c("Orange Juice","Ascorbic Acid"))
```


## Orange Juice vs Ascorbic Acid at 0.5 dose level
Ascorbic acid seems to provide less tooth growth for dose levels 0.5 and 1.0. Let us check these hypotheses with t-test as follows H0: mu=0, H1: mu<0

```{R Test hypothesis for dose level 0.5}
OJ5<-subset(ToothGrowth,supp=="OJ" & dose==.5,
            select = len) # Ornage Juice, 0.5 dose
VC5<-subset(ToothGrowth,supp=="VC" & dose==.5,
            select = len) # Ascorbic Acid, 0.5 dose
t.test(VC5,OJ5,alternative="less") 
```

#### Conclusion:
We reject Null hypothesis and accept alternative. It means **ascorbic acid provides less tooth growth for 0.5 dose level  with 95% confidence**.

## Orange Juice vs Ascorbic Acid at 1.0 dose level
Let us check 1.0 dose.
```{R Test hypothesis for dose level 1.0}
OJ10<-subset(ToothGrowth,supp=="OJ" & dose==1.0,
            select = len) # Ornage Juice, 1.0 dose
VC10<-subset(ToothGrowth,supp=="VC" & dose==1.0,
            select = len) # Ascorbic Acid, 1.0 dose
t.test(VC10,OJ10,alternative="less") 
```

#### Conclusion:
The same result as for 0.5 dose. We reject Null hypothesis and accept alternative. It means **ascorbic acid provides less tooth growth for  1.0 dose level with 95% confidence.**

## Orange Juice vs Ascorbic Acid at 2.0 dose level
Let us check 2.0 dose. H0: mu=0, H1: mu!=0

```{R Test hypothesis for dose level 2.0}
OJ20<-subset(ToothGrowth,supp=="OJ" & dose==2.0,
            select = len) # Ornage Juice, 2.0 dose
VC20<-subset(ToothGrowth,supp=="VC" & dose==2.0,
            select = len) # Ascorbic Acid, 1.0 dose
t.test(VC20,OJ20,var.equal = TRUE) 
```

#### Conclusion:
We can not reject null hypothesis since p-value is large and confidence interval contains zero. It means that **orange juice and ascorbic acid provide the same tooth growth for 2.0 dose level with 95% confidence.**
